baseurl: ''
relativeurls: true
languageCode: en
pluralizelisttitles: false
removePathAccents: true
title: Internet Pawpaw Movie Database

disableKinds:
  - taxonomyTerm

params:
  Description: >-
    Useful resources for using IPFS and building things on top of it
  image: /images/banner.png
